import { jsPDF } from "jspdf";
import type { ChatHistoryItem, UserProfile } from "./api";
import { sendChat } from "./api";

const GREEN: [number, number, number] = [76, 175, 96];
const ORANGE: [number, number, number] = [240, 138, 48];
const YELLOW: [number, number, number] = [240, 196, 25];
const DARK: [number, number, number] = [38, 50, 56];

export async function generateSummaryPdf(
  history: ChatHistoryItem[],
  user: UserProfile | null,
) {
  // Ask the AI to write a clean structured summary of the conversation
  const transcript = history
    .map((h) => `${h.sender === "user" ? "USER" : "NUTRIBOT"}: ${h.message}`)
    .join("\n");

  const prompt =
    "Write a concise, well-structured summary of the following NutriBot consultation session. " +
    "Use clean Markdown with sections: ## Profile, ## Goal, ## Key Insights, ## Meal Recommendations, ## Action Items. " +
    "Do NOT copy the raw conversation. Make it tight and actionable. Reply in English only.\n\n" +
    transcript;

  const { reply } = await sendChat({ message: prompt, history: [], context: user ?? undefined });

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // White background already; draw gradient-like bar at top
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, W, 80, "F");
  doc.setFillColor(...ORANGE);
  doc.rect(W * 0.55, 0, W * 0.3, 80, "F");
  doc.setFillColor(...YELLOW);
  doc.rect(W * 0.82, 0, W * 0.18, 80, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("NutriBot Summary", 40, 50);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleString(), 40, 68);

  let y = 110;
  if (user) {
    doc.setTextColor(...DARK);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`User: ${user.username}`, 40, y);
    y += 16;
    doc.setFont("helvetica", "normal");
    const meta = [
      user.age != null ? `Age: ${user.age}` : null,
      user.gender ? `Gender: ${user.gender}` : null,
      user.height != null ? `Height: ${user.height} cm` : null,
      user.weight != null ? `Weight: ${user.weight} kg` : null,
      user.goal ? `Goal: ${user.goal}` : null,
      user.activity_level ? `Activity: ${user.activity_level}` : null,
    ].filter(Boolean).join("  •  ");
    if (meta) {
      doc.setFontSize(10);
      doc.text(meta, 40, y);
      y += 20;
    }
  }

  // Divider
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(2);
  doc.line(40, y, W - 40, y);
  y += 18;

  // Body — render markdown-ish lines with colored headings
  doc.setTextColor(...DARK);
  const lines = reply.split("\n");
  for (const raw of lines) {
    const line = raw.replace(/\*\*/g, "").trimEnd();
    if (y > H - 60) { doc.addPage(); y = 50; }
    if (line.startsWith("## ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(15);
      doc.setTextColor(...ORANGE);
      doc.text(line.slice(3), 40, y);
      y += 22;
    } else if (line.startsWith("# ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(18);
      doc.setTextColor(...GREEN);
      doc.text(line.slice(2), 40, y);
      y += 26;
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(...DARK);
      const wrapped = doc.splitTextToSize("•  " + line.slice(2), W - 100);
      doc.text(wrapped, 56, y);
      y += wrapped.length * 14 + 2;
    } else if (!line) {
      y += 6;
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(...DARK);
      const wrapped = doc.splitTextToSize(line, W - 80);
      doc.text(wrapped, 40, y);
      y += wrapped.length * 14 + 2;
    }
  }

  // Footer band
  doc.setFillColor(...YELLOW);
  doc.rect(0, H - 24, W, 24, "F");
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.text("Generated by NutriBot — AI-powered nutrition assistant", 40, H - 8);

  doc.save(`nutribot-summary-${Date.now()}.pdf`);
}
